config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'product_index#index'

  get '/webpay_plus/create', to: 'webpay_plus#create'
  get '/webpay_plus/commit', to: 'webpay_plus#commit'
  get '/webpay_plus/status', to: 'webpay_plus#status'
  post '/webpay_plus/refund', to: 'webpay_plus#refund'
  get '/webpay_plus/refund', to: 'webpay_plus#show_refund'

  get '/webpay_plus_deferred/create', to: 'webpay_plus_deferred#create'
  get '/webpay_plus_deferred/commit', to: 'webpay_plus_deferred#commit'
  post '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#capture'
  get '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#show_capture'
  get '/webpay_plus_deferred/status', to: 'webpay_plus_deferred#status'
  post '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#refund'
  get '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#show_refund'
  # post '/webpay_plus_deferred/increase_amount', to: 'webpay_plus_deferred#increase_amount'
  # post '/webpay_plus_deferred/reverse', to: 'webpay_plus_deferred#reverse'
  # post '/webpay_plus_deferred/increase_date', to: 'webpay_plus_deferred#increase_date'
  # post '/webpay_plus_deferred/history', to: 'webpay_plus_deferred#history'

  get '/webpay_plus_mall/create', to: 'webpay_plus_mall#create'
  get '/webpay_plus_mall/commit', to: 'webpay_plus_mall#commit'
  get '/webpay_plus_mall/status', to: 'webpay_plus_mall#status'
  post '/webpay_plus_mall/refund', to: 'webpay_plus_mall#refund'
  get '/webpay_plus_mall/refund', to: 'webpay_plus_mall#show_refund'

  get '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#create'
  post '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#send_create'
  get '/webpay_plus_mall_deferred/commit', to: 'webpay_plus_mall_deferred#commit'
  post 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#capture'
  get 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#show_capture'
  get '/webpay_plus_mall_deferred/status', to: 'webpay_plus_mall_deferred#status'
  post '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#refund'
  get '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#show_refund'
  # post '/webpay_plus_mall_deferred/increase_amount', to: 'webpay_plus_mall_deferred#increase_amount'
  # post '/webpay_plus_mall_deferred/reverse', to: 'webpay_plus_mall_deferred#reverse'
  # post '/webpay_plus_mall_deferred/increase_date', to: 'webpay_plus_mall_deferred#increase_date'
  # post '/webpay_plus_mall_deferred/history', to: 'webpay_plus_mall_deferred#history'

  get '/oneclick_mall/start', to: 'oneclick_mall#start'
  get '/oneclick_mall/finish', to: 'oneclick_mall#finish'
  delete '/oneclick_mall/delete', to: 'oneclick_mall#delete'
  get '/oneclick_mall/authorize', to: 'oneclick_mall#authorize'
  get '/oneclick_mall/status', to: 'oneclick_mall#status'
  post '/oneclick_mall/refund', to: 'oneclick_mall#refund'
  get '/oneclick_mall/refund', to: 'oneclick_mall#show_refund'

  get '/oneclick_mall_deferred/start', to: 'oneclick_mall_deferred#start'
  get '/oneclick_mall_deferred/finish', to: 'oneclick_mall_deferred#finish'
  delete '/oneclick_mall_deferred/delete', to: 'oneclick_mall_deferred#delete'
  get '/oneclick_mall_deferred/authorize', to: 'oneclick_mall_deferred#authorize'
  get '/oneclick_mall_deferred/status', to: 'oneclick_mall_deferred#status'
  post '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#refund'
  get '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#show_refund'
  post '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#capture'
  get '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#show_capture'
  # post '/oneclick_mall_deferred/increase_amount', to: 'oneclick_mall_deferred#increase_amount'
  # post '/oneclick_mall_deferred/reverse', to: 'oneclick_mall_deferred#reverse'
  # post '/oneclick_mall_deferred/increase_date', to: 'oneclick_mall_deferred#increase_date'
  # post '/oneclick_mall_deferred/history', to: 'oneclick_mall_deferred#history'

  get '/transaccion_completa/form', to: 'transaccion_completa#form'
  post '/transaccion_completa/create', to: 'transaccion_completa#create'
  get '/transaccion_completa/create', to: 'transaccion_completa#show_create'
  post '/transaccion_completa/installments', to: 'transaccion_completa#installments'
  get '/transaccion_completa/installments', to: 'transaccion_completa#show_installments'
  post '/transaccion_completa/commit', to: 'transaccion_completa#commit'
  get '/transaccion_completa/commit', to: 'transaccion_completa#show_commit'
  get  '/transaccion_completa/status', to: 'transaccion_completa#status'
  post '/transaccion_completa/refund', to: 'transaccion_completa#refund'
  get '/transaccion_completa/refund', to: 'transaccion_completa#show_refund'

  get '/transaccion_completa_deferred/form', to: 'transaccion_completa_deferred#form'
  post '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#create'
  get '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#show_create'
  post '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#installments'
  get '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#show_installments'
  post '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#commit'
  get '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#show_commit'
  post '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#capture'
  get '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#show_capture'
  get  '/transaccion_completa_deferred/status', to: 'transaccion_completa_deferred#status'
  post '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#refund'
  get '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#show_refund'
  # post '/transaccion_completa_deferred/increase_amount', to: 'transaccion_completa_deferred#increase_amount'
  # post '/transaccion_completa_deferred/reverse', to: 'transaccion_completa_deferred#reverse'
  # post '/transaccion_completa_deferred/increase_date', to: 'transaccion_completa_deferred#increase_date'
  # post '/transaccion_completa_deferred/history', to: 'transaccion_completa_deferred#history'

  get '/transaccion_completa_mall/form', to: 'transaccion_completa_mall#form'
  post '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#create'
  get '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#show_create'
  post '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#installments'
  get '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#show_installments'
  post '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#commit'
  get '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#show_commit'
  get  '/transaccion_completa_mall/status', to: 'transaccion_completa_mall#status'
  post '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#refund'
  get '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#show_refund'

  get '/transaccion_completa_mall_deferred/form', to: 'transaccion_completa_mall_deferred#form'
  post '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#create'
  get '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#show_create'
  post '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#installments'
  get '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#show_installments'
  post '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#commit'
  get '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#show_commit'
  post '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#capture'
  get '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#show_capture'
  get  '/transaccion_completa_mall_deferred/status', to: 'transaccion_completa_mall_deferred#status'
  post '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#refund'
  get '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#show_refund'
  # post '/transaccion_completa_mall_deferred/increase_amount', to: 'transaccion_completa_mall_deferred#increase_amount'
  # post '/transaccion_completa_mall_deferred/reverse', to: 'transaccion_completa_mall_deferred#reverse'
  # post '/transaccion_completa_mall_deferred/increase_date', to: 'transaccion_completa_mall_deferred#increase_date'
  # post '/transaccion_completa_mall_deferred/history', to: 'transaccion_completa_mall_deferred#history'

  get '/patpass_comercio/start', to: 'patpass_comercio#start'
  post '/patpass_comercio/commit', to: 'patpass_comercio#commit'
  post '/patpass_comercio/commit', to: 'patpass_comercio#show_commit'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#voucher_return'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#show_voucher_return'

end

app/controllers/transaccion_completa_mall_deferred_controller.rb
class TransaccionCompletaMallDeferredController < ApplicationController
  skip_before_action :verify_authenticity_token

  def initialize
    super
    @tx = Transbank::Webpay::TransaccionCompleta::MallTransaction.new(
      ::Transbank::Common::IntegrationCommerceCodes::TRANSACCION_COMPLETA_MALL_DEFERRED,
      ::Transbank::Common::IntegrationApiKeys::WEBPAY, :integration)
    @child_commerce_codes = [::Transbank::Common::IntegrationCommerceCodes::TRANSACCION_COMPLETA_MALL_DEFERRED_CHILD1   , ::Transbank::Common::IntegrationCommerceCodes::TRANSACCION_COMPLETA_MALL_DEFERRED_CHILD2   ]
  end

  def form
  end

  def create
    @req = params.as_json

    @buy_order = @req['buy_order']
    @session_id = @req['session_id']
    @card_number = @req['number'].delete(' ')
    expiry_year = @req['expiry_year']
    expiry_month = @req['expiry_month']
    @cvv = @req['cvc']
    @card_expiration_date ="#{expiry_year}/#{expiry_month}"
    @details =  [
      {
        "commerce_code": ::Transbank::Common::IntegrationCommerceCodes::TRANSACCION_COMPLETA_MALL_DEFERRED_CHILD1,
        "buy_order": "childBuyOrder1_#{rand(1000)}",
        "amount": "1000"
      },
      {
        "commerce_code": ::Transbank::Common::IntegrationCommerceCodes::TRANSACCION_COMPLETA_MALL_DEFERRED_CHILD2,
        "buy_order": "childBuyOrder2_#{rand(1000)}",
        "amount": "2000"
      }
    ]
    

    @resp = @tx.create(@buy_order, @session_id, @card_number, @card_expiration_date, @details, @cvv)  
    
    redirect_to transaccion_completa_mall_deferred_create_path(resp: @resp, details: @details)
  end

  def show_create
    @details = params[:details]
    @resp = params[:resp]
  end

  def installments
    @req = params.as_json
    @token = @req['token']
    @details = @req['detail']['details']
    @resp = @tx.installments(@token, @details)  
    
    redirect_to transaccion_completa_mall_deferred_installments_path(token: @token, details: @details, resp: @resp)
  end

  def show_installments
    @token = params[:token]
    @details = params[:details]
    @resp = params[:resp]
  end

  def commit
    @req = params.as_json
    @token = @req['token']
    @details = @req['detail']['details']
    @resp = @tx.commit(@token, @details)  
    

    @detail = @resp['details'][0]
    @amount = @detail['amount']
    @buy_order = @detail['buy_order']
    @authorization_code = @detail['authorization_code']
    @child_commerce_code = @detail['commerce_code']
    redirect_to transaccion_completa_mall_deferred_commit_path(token: @token,
      buy_order:@buy_order,
      details: @details,
      amount: @amount,
      authorization_code: @authorization_code,
      child_commerce_code: @child_commerce_code,
      resp: @resp)
  end

  def show_commit
    @token = params[:token]
    @details = params[:details]
    @resp = params[:resp]
    @amount = params[:amount]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @child_commerce_code = params[:child_commerce_code]
  end


  def status
    @req = params.as_json
    @token = @req['token']
    @resp = @tx.status(@token)  
    
  end

  def refund
    @req = params.as_json
    @token = @req['token']
    @amount = @req['amount']
    @child_buy_order = @req['child_buy_order']
    @child_commerce_code = @req['child_commerce_code']
    @resp = @tx.refund(@token, @child_buy_order, @child_commerce_code, @amount)  
    
    redirect_to transaccion_completa_mall_deferred_refund_path(token: @token, child_buy_order: @child_buy_order, child_commerce_code: @child_commerce_code, amount: @amount, resp: @resp)
  end

  def show_refund
    @token = params[:token]
    @child_buy_order = params[:child_buy_order]
    @child_commerce_code = params[:child_commerce_code]
    @amount = params[:amount]
    @resp = params[:resp]
  end

  def capture
    @req = params.as_json
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @child_commerce_code = params[:commerce_code]
    @resp = @tx.capture(@token, @child_commerce_code, @buy_order, @authorization_code, @amount)
    
    redirect_to transaccion_completa_mall_deferred_capture_path(token: @token, child_commerce_code:@child_commerce_code, buy_order: @buy_order, authorization_code: @authorization_code, amount: @amount, resp: @resp)
  end

  def show_capture
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = params[:resp]
    @child_commerce_code = params[:child_commerce_code]
  end

end

app/views/transaccion_completa_mall_deferred/form.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "txcompleta.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h2>Formulario</h2>
  <p>Para poder comenzar con la transacción primero necesitas obtener los datos de la tarjeta de crédito del tarjetahabiente.</p>

  <div class="TBK-content-left">
    <div>
      <h3>Formulario de pago</h3>
      <p>Para comenzar debes obtener los datos de la tarjeta sobre la cual se desea generar una transacción.</p>
    </div>

    <div class="TBK-card">
      <div>
        <%= form_with url: transaccion_completa_mall_deferred_create_path, data: { remote: false }, id:"card", method: :post do |form| %>
          <div class="card-wrapper mb-30">
          </div>
          <%= form.hidden_field :buy_order, value: "buyorder#{Time.zone.now.to_i}", class: "TBK-input" %>
          <%= form.hidden_field :session_id, value: "session_id#{Time.zone.now.to_i}", class: "TBK-input" %>
          <%= form.label :number, "Numedo de tarjeta" %>
          <%= form.text_field :number, value: "4051 8856 0044 6623", placeholder:"1234 1234 1234 1234",  class: "TBK-input" %>

          <div class="TBK-input-group">
            <div>
              <%= form.label :expiry_month, "Mes" %>
              <%= form.text_field :expiry_month, value: "12", class: "TBK-input" %>
            </div>
            <div>
              <%= form.label :expiry_year, "Año", placeholder:"AA" %>
              <%= form.text_field :expiry_year, value:"29", class: "TBK-input" %>
            </div>
            <div>
              <%= form.label :cvc, "CVV", placeholder:"CVV" %>
              <%= form.text_field :cvc, value: "123", class: "TBK-input" %>
            </div>
          </div>

          <%= form.label :amount, "monto" %>
          <%= form.text_field :amount, value: "1000", class: "TBK-input" %>
          <%= form.submit "PAGAR", class: "TBK-button" %>
        <% end %>
      </div>
    </div>
  </div>

  <script>
    var card = new Card({
      form: 'form#card',
      container: '.card-wrapper',
      messages: {
        monthYear: 'mm/yy',
      },
      placeholders: {
        name: '**** ****'
      },
      formSelectors: {
        expiryInput: 'input[name=expiry_month], input[name=expiry_year]', // optional — default input[name="expiry"]
      },
      debug: true
    });
  </script>

</div>

app/views/transaccion_completa_mall_deferred/show_capture.html.erb
<div class="TBK-container">
	<div class="TBK-main-image">
    <%= image_tag "txcompleta.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>
  <h2>Capturar Transacción Mall diferida</h2>
  <p>En este paso debemos capturar la transacción para realmente capturar el dinero que habia sido previamente reservado al hacer la transacción</p>

  <div class="TBK-content-left">
		<div>
			<h3>Petición</h3>
			<p>
        Para capturar una transacción necesitaremos el código de comercio de la tienda hija, Token, Orden de compra, Código de autorización y monto a capturar. Se hace de la siguiente manera.
      </p>
		</div>
    <%= render_markdown_highlighting("transaccion_completa_mall_deferred/partials/capture-mark1.md") %>
	</div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
		<div class="item-right">
			<h3>Respuesta</h3>
			<p>Transbank contestará con lo siguiente. Debes guardar esta información, lo único que debes validar es que response_code sea igual a cero.</p>
		</div>
	</div>

  <div class="TBK-content-left">
    <div class="aling-s-baseline">
		  <%= link_to "CONSULTAR ESTADO", transaccion_completa_mall_deferred_status_path(token: @token), class:"TBK-button aling-s-baseline" %>
    </div>
    <div>
      <%= form_with url: transaccion_completa_mall_deferred_refund_path, data: { remote: false }, method: :post do |form| %>
        <%= form.hidden_field  :token, value: @token, class: "TBK-input" %>
        
        <%= form.label :child_commerce_code, "Codigo de comercio (hijo)" %>
        <%= form.text_field    :child_commerce_code, value:  @child_commerce_code, class: "TBK-input" %>
        <%= form.label :child_buy_order, "Orden de compra" %>
        <%= form.text_field    :child_buy_order, value:  @buy_order, class: "TBK-input" %>
        <%= form.label :amount, "Monto" %>
        <%= form.text_field    :amount, value:  @amount, class: "TBK-input" %>

        <%= form.submit "REEMBOLSAR", class: "TBK-button mb-30" %>
      <% end %>

    </div>
	</div>

</div>

app/views/transaccion_completa_mall_deferred/show_commit.html.erb
<div class="TBK-container">
	<div class="TBK-main-image">
    <%= image_tag "txcompleta.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>
  <h2>Confirmar Transacción</h2>
  <p>En este paso tenemos que confirmar la transacción con el objetivo de avisar a Transbank que hemos recibido la transacción ha sido recibida exitosamente. En caso de que no se confirme la transacción, ésta será reversada.</p>

  <div class="TBK-content-left">
		<div>
			<h3>Petición</h3>
			<p>
        Para poder confirmar la transacción debes enviar el token, y en caso de pago en cuotas debes también enviar el ID de la consulta de cuotas. En algunos casos tambien debes enviar el Indice del periodo diferido y un boolean indicando si se tomará el período de gracia.
      </p>
		</div>
    <%= render_markdown_highlighting("transaccion_completa_mall_deferred/partials/commit-mark1.md") %>
	</div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
		<div class="item-right">
			<h3>Respuesta</h3>
			<p>Una vez confirmada la transacción recibirás la siguiente información.</p>
		</div>
	</div>

  <h2 class="m-none">Casi listo !</h2>
  <p class="mb-30">Ya puedes mostrar al usuario una página de éxito de la transacción. Debes tener en cuenta que la transacción aun no ha sido capturada solo ha sido retenido el saldo en la tarjeta del Tarjetahabiente. Luego de confirmar la transacción podemos:</p>

  <%= render "/deferred/deferred-options" %>

  <div class="TBK-content-left">
    <div>
      <h3>comercio 1</h3>
      <%= form_with url: transaccion_completa_mall_deferred_capture_path, data: { remote: false }, method: :post do |form| %>
        <%= form.hidden_field :token, value: @token%>
        <%= form.hidden_field :child_commerce_code, value:  @resp["details"].first['commerce_code'] %>
        <%= form.hidden_field :buy_order, value:  @resp["details"].first['buy_order'] %>
        <%= form.hidden_field :authorization_code, value: @resp["details"].first['authorization_code']  %>

        <%= form.label :amount, "monto (hijo 1)" %>
        <%= form.text_field :amount, value:  @resp["details"].first['amount'], class: "TBK-input" %>
        <%= form.submit "CAPTURAR", class: "TBK-button mb-30" %>
      <% end %>
    </div>

    <div>
      <h3>comercio 2</h3>
      <%= form_with url: transaccion_completa_mall_deferred_capture_path, data: { remote: false }, method: :post do |form| %>
        <%= form.hidden_field :token, value: @token%>
        <%= form.hidden_field :child_commerce_code, value:  @resp["details"].second['commerce_code'] %>
        <%= form.hidden_field :buy_order, value:  @resp["details"].second['buy_order'] %>
        <%= form.hidden_field :authorization_code, value: @resp["details"].second['authorization_code']  %>

        <%= form.label :amount, "monto (hijo 2)" %>
        <%= form.text_field :amount, value:  @resp["details"].second['amount'], class: "TBK-input" %>
        
        <%= form.submit "CAPTURAR", class: "TBK-button mb-30" %>
      <% end %>
    </div>

    
  </div>  
</div>

app/views/transaccion_completa_mall_deferred/show_create.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "txcompleta.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>
  <h2>Crear Transacción</h2>
  <p>En este paso crearemos la transacción con el objetivo de obtener un identificador unico.</p>

  <div class="TBK-content-left">
		<div>
			<h3>Petición</h3>
			<p>Para comenzar debes hacer una instancia de TransaccionCompleta y luego crear una transacción</p>
		</div>
    <%= render_markdown_highlighting("transaccion_completa_mall_deferred/partials/create-mark1.md") %>
	</div>

 <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
		<div class="item-right">
			<h3>Respuesta</h3>
			<p>Una vez creada la transacción, estos serán los datos de respuesta</p>
		</div>
	</div>

  <h2>Lo siguiente ...</h2>
  <p>
  Ahora que ya creamos la transacción tienes dos opciones, puedes hacer consultas de cuotas para pagar con ellas o puedes directamente confirmar la transacción
  </p>

  <div class="TBK-content-left">
    <%= form_with url: transaccion_completa_mall_deferred_commit_path, data: { remote: false }, method: :post do |form| %>
      <%= form.hidden_field :token, value: @resp["token"] %>
      <%= form.hidden_field "detail[details][][commerce_code]", value: @details.first[:commerce_code] %>
      <%= form.hidden_field "detail[details][][buy_order]", value: @details.first[:buy_order] %>
      <%= form.hidden_field "detail[details][][commerce_code]", value: @details.second[:commerce_code] %>
      <%= form.hidden_field "detail[details][][buy_order]", value: @details.second[:buy_order] %>
      <%= form.submit "CONFIRMAR", class: "TBK-button" %>
    <% end %>
 
    <%= form_with url: transaccion_completa_mall_deferred_installments_path, data: { remote: false }, method: :post do |form| %>
      <%= form.hidden_field :token, value: @resp["token"] %>
      <%= form.hidden_field "detail[details][][commerce_code]", value: @details.first[:commerce_code] %>
      <%= form.hidden_field "detail[details][][buy_order]", value: @details.first[:buy_order] %>
      <%= form.hidden_field "detail[details][][amount]", value: @details.first[:amount] %>
      <%= form.label "detail[details][][installments_number]", "cuotas comercio hijo 1"%>
      <%= form.number_field  "detail[details][][installments_number]", value: 2, class: "TBK-input" %>

      <%= form.hidden_field "detail[details][][commerce_code]", value: @details.second[:commerce_code] %>
      <%= form.hidden_field "detail[details][][buy_order]", value: @details.second[:buy_order] %>
      <%= form.hidden_field "detail[details][][amount]", value: @details.second[:amount] %>
      <%= form.label "detail[details][][installments_number]", "cuotas comercio hijo 2"%>
      <%= form.number_field  "detail[details][][installments_number]", value: 2, class: "TBK-input" %>
      <%= form.submit "HACER CONSULTA DE CUOTAS", class: "TBK-button" %>
    <% end %>
  </div>

</div>

app/views/transaccion_completa_mall_deferred/show_refund.html.erb
<div class="TBK-container">
  <div   iv class="TBK-main-image">
    <%= image_tag "txcompleta.png" , alt: "transaccion-completa" , class:"adjusted-image" %>
  </div>

  <h1>Reembolso de Transacción Mall diferida</h1>

  <p>
    Podrás pedir el reembolso del dinero al tarjeta habiente,
    dependiendo del monto y el tiempo transacurrido será una Reversa, Anulación o Anulación parcial.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>
        Necesitas el token de la transacción y el monto que quieres reversar,
        si anulas el monto total puede ser una Reversa o Anulación dependiendo de ciertas condiciones
        o una Anulación parcial si el monto es menor al total.
        No es posible hacer ni Anulaciones ni Anulaciones parciales en tarjetas que no sean de crédito.
        Tampoco es posible realizar reembolsos de compras en cuotas.
      </p>
    </div>
    <%= render_markdown_highlighting("transaccion_completa_mall_deferred/partials/refund-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Transbank contestará con el resultado de la reversa o anulación.</p>
    </div>
  </div>
  

</div>