config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'product_index#index'

  get '/webpay_plus/create', to: 'webpay_plus#create'
  get '/webpay_plus/commit', to: 'webpay_plus#commit'
  get '/webpay_plus/status', to: 'webpay_plus#status'
  post '/webpay_plus/refund', to: 'webpay_plus#refund'
  get '/webpay_plus/refund', to: 'webpay_plus#show_refund'

  get '/webpay_plus_deferred/create', to: 'webpay_plus_deferred#create'
  get '/webpay_plus_deferred/commit', to: 'webpay_plus_deferred#commit'
  post '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#capture'
  get '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#show_capture'
  get '/webpay_plus_deferred/status', to: 'webpay_plus_deferred#status'
  post '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#refund'
  get '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#show_refund'
  # post '/webpay_plus_deferred/increase_amount', to: 'webpay_plus_deferred#increase_amount'
  # post '/webpay_plus_deferred/reverse', to: 'webpay_plus_deferred#reverse'
  # post '/webpay_plus_deferred/increase_date', to: 'webpay_plus_deferred#increase_date'
  # post '/webpay_plus_deferred/history', to: 'webpay_plus_deferred#history'

  get '/webpay_plus_mall/create', to: 'webpay_plus_mall#create'
  get '/webpay_plus_mall/commit', to: 'webpay_plus_mall#commit'
  get '/webpay_plus_mall/status', to: 'webpay_plus_mall#status'
  post '/webpay_plus_mall/refund', to: 'webpay_plus_mall#refund'
  get '/webpay_plus_mall/refund', to: 'webpay_plus_mall#show_refund'

  get '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#create'
  post '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#send_create'
  get '/webpay_plus_mall_deferred/commit', to: 'webpay_plus_mall_deferred#commit'
  post 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#capture'
  get 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#show_capture'
  get '/webpay_plus_mall_deferred/status', to: 'webpay_plus_mall_deferred#status'
  post '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#refund'
  get '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#show_refund'
  # post '/webpay_plus_mall_deferred/increase_amount', to: 'webpay_plus_mall_deferred#increase_amount'
  # post '/webpay_plus_mall_deferred/reverse', to: 'webpay_plus_mall_deferred#reverse'
  # post '/webpay_plus_mall_deferred/increase_date', to: 'webpay_plus_mall_deferred#increase_date'
  # post '/webpay_plus_mall_deferred/history', to: 'webpay_plus_mall_deferred#history'

  get '/oneclick_mall/start', to: 'oneclick_mall#start'
  get '/oneclick_mall/finish', to: 'oneclick_mall#finish'
  delete '/oneclick_mall/delete', to: 'oneclick_mall#delete'
  get '/oneclick_mall/authorize', to: 'oneclick_mall#authorize'
  get '/oneclick_mall/status', to: 'oneclick_mall#status'
  post '/oneclick_mall/refund', to: 'oneclick_mall#refund'
  get '/oneclick_mall/refund', to: 'oneclick_mall#show_refund'

  get '/oneclick_mall_deferred/start', to: 'oneclick_mall_deferred#start'
  get '/oneclick_mall_deferred/finish', to: 'oneclick_mall_deferred#finish'
  delete '/oneclick_mall_deferred/delete', to: 'oneclick_mall_deferred#delete'
  get '/oneclick_mall_deferred/authorize', to: 'oneclick_mall_deferred#authorize'
  get '/oneclick_mall_deferred/status', to: 'oneclick_mall_deferred#status'
  post '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#refund'
  get '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#show_refund'
  post '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#capture'
  get '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#show_capture'
  # post '/oneclick_mall_deferred/increase_amount', to: 'oneclick_mall_deferred#increase_amount'
  # post '/oneclick_mall_deferred/reverse', to: 'oneclick_mall_deferred#reverse'
  # post '/oneclick_mall_deferred/increase_date', to: 'oneclick_mall_deferred#increase_date'
  # post '/oneclick_mall_deferred/history', to: 'oneclick_mall_deferred#history'

  get '/transaccion_completa/form', to: 'transaccion_completa#form'
  post '/transaccion_completa/create', to: 'transaccion_completa#create'
  get '/transaccion_completa/create', to: 'transaccion_completa#show_create'
  post '/transaccion_completa/installments', to: 'transaccion_completa#installments'
  get '/transaccion_completa/installments', to: 'transaccion_completa#show_installments'
  post '/transaccion_completa/commit', to: 'transaccion_completa#commit'
  get '/transaccion_completa/commit', to: 'transaccion_completa#show_commit'
  get  '/transaccion_completa/status', to: 'transaccion_completa#status'
  post '/transaccion_completa/refund', to: 'transaccion_completa#refund'
  get '/transaccion_completa/refund', to: 'transaccion_completa#show_refund'

  get '/transaccion_completa_deferred/form', to: 'transaccion_completa_deferred#form'
  post '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#create'
  get '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#show_create'
  post '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#installments'
  get '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#show_installments'
  post '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#commit'
  get '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#show_commit'
  post '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#capture'
  get '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#show_capture'
  get  '/transaccion_completa_deferred/status', to: 'transaccion_completa_deferred#status'
  post '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#refund'
  get '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#show_refund'
  # post '/transaccion_completa_deferred/increase_amount', to: 'transaccion_completa_deferred#increase_amount'
  # post '/transaccion_completa_deferred/reverse', to: 'transaccion_completa_deferred#reverse'
  # post '/transaccion_completa_deferred/increase_date', to: 'transaccion_completa_deferred#increase_date'
  # post '/transaccion_completa_deferred/history', to: 'transaccion_completa_deferred#history'

  get '/transaccion_completa_mall/form', to: 'transaccion_completa_mall#form'
  post '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#create'
  get '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#show_create'
  post '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#installments'
  get '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#show_installments'
  post '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#commit'
  get '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#show_commit'
  get  '/transaccion_completa_mall/status', to: 'transaccion_completa_mall#status'
  post '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#refund'
  get '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#show_refund'

  get '/transaccion_completa_mall_deferred/form', to: 'transaccion_completa_mall_deferred#form'
  post '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#create'
  get '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#show_create'
  post '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#installments'
  get '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#show_installments'
  post '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#commit'
  get '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#show_commit'
  post '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#capture'
  get '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#show_capture'
  get  '/transaccion_completa_mall_deferred/status', to: 'transaccion_completa_mall_deferred#status'
  post '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#refund'
  get '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#show_refund'
  # post '/transaccion_completa_mall_deferred/increase_amount', to: 'transaccion_completa_mall_deferred#increase_amount'
  # post '/transaccion_completa_mall_deferred/reverse', to: 'transaccion_completa_mall_deferred#reverse'
  # post '/transaccion_completa_mall_deferred/increase_date', to: 'transaccion_completa_mall_deferred#increase_date'
  # post '/transaccion_completa_mall_deferred/history', to: 'transaccion_completa_mall_deferred#history'

  get '/patpass_comercio/start', to: 'patpass_comercio#start'
  post '/patpass_comercio/commit', to: 'patpass_comercio#commit'
  post '/patpass_comercio/commit', to: 'patpass_comercio#show_commit'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#voucher_return'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#show_voucher_return'

end

app/controllers/oneclick_mall_deferred_controller.rb
class OneclickMallDeferredController < ApplicationController
  skip_before_action :verify_authenticity_token

  def initialize
    super
    @inscription = Transbank::Webpay::Oneclick::MallInscription.new(::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED, ::Transbank::Common::IntegrationApiKeys::WEBPAY, :integration)
    @tx = Transbank::Webpay::Oneclick::MallTransaction.new(::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED, ::Transbank::Common::IntegrationApiKeys::WEBPAY, :integration)
    @ctrl = "oneclick_mall_deferred"
  end

  def start
    @req = params.as_json
    @user_name = "User-#{rand(1000)}"
    @email = "user.#{rand(1000)}@example.com"
    @response_url = "#{root_url}#{@ctrl}/finish"
    session[:user_name] = @user_name
    session[:email] = @email
    @resp = @inscription.start(@user_name, @email, @response_url)  
    
  end

  def finish
    @req = params.as_json
    @token = @req["TBK_TOKEN"]
    @child_commerce_codes = [::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED_CHILD1, ::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED_CHILD2]
    @user_name = session[:user_name]
    @resp = @inscription.finish(@token)  
    
  end

  def delete
    @req = params.as_json
    #binding.pry
    @user_name = @req['user_name']
    @tbk_user = @req['tbk_user']
    @resp = @inscription.delete(@tbk_user, @user_name)
    
  end

  def authorize
    @req = params.as_json
    @username = session[:user_name]
    @tbk_user = @req['tbk_user']
    @buy_order = "buyOrder_#{rand(1000)}"
    @details =[
      {
        commerce_code: ::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED_CHILD1,
        buy_order: "childBuyOrder1_#{rand(1000)}",
        amount: 1000,
        installments_number: 1
      },
      {
        commerce_code: ::Transbank::Common::IntegrationCommerceCodes::ONECLICK_MALL_DEFERRED_CHILD2,
        buy_order: "childBuyOrder2_#{rand(1000)}",
        amount: 2000,
        installments_number: 1
      }
    ]
    @resp = @tx.authorize(@username, @tbk_user, @buy_order, @details)
    

    @detail = @resp['details'][0]
    @amount = @detail['amount']
    @child_buy_order = @detail['buy_order']
    @authorization_code = @detail['authorization_code']
    @child_commerce_code = @detail['commerce_code']
  end

  def status
    @req = params.as_json
    @buy_order = params[:buy_order]
    @resp = @tx.status(@buy_order)
    
  end

  def refund
    @req = params.as_json
    @buy_order = params[:buy_order]
    @child_buy_order = params[:child_buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @child_commerce_code = params[:commerce_code]
    @resp = @tx.refund(@buy_order, @child_commerce_code, @child_buy_order, @amount)
    
    redirect_to oneclick_mall_deferred_refund_path(buy_order: @buy_order, child_commerce_code: @child_commerce_code, child_buy_order: @child_buy_order, amount: @amount, resp: @resp)
  end

  def show_refund
    @buy_order = params[:buy_order]
    @child_commerce_code = params[:child_commerce_code]
    @child_buy_order = params[:child_buy_order]
    @amount = params[:amount]
    @resp = params[:resp]
  end

  def capture
    @req = params.as_json
    @buy_order = params[:buy_order]
    @child_buy_order = params[:child_buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @child_commerce_code = params[:commerce_code]

    @resp = @tx.capture(@child_commerce_code, @child_buy_order, @authorization_code, @amount)  
    redirect_to oneclick_mall_deferred_capture_path(buy_order: @buy_order, child_commerce_code: @child_commerce_code, child_buy_order: @child_buy_order, amount: @amount, resp: @resp)
  end

  def show_capture
    @buy_order = params[:buy_order]
    @child_commerce_code = params[:child_commerce_code]
    @child_buy_order = params[:child_buy_order]
    @amount = params[:amount]
    @resp = params[:resp]
    redirect_to oneclick_mall_deferred_capture_path(buy_order: @buy_order, child_commerce_code: @child_commerce_code, child_buy_order: @child_buy_order, amount: @amount, resp: @resp)
  end

end

app/views/oneclick_mall_deferred/authorize.html.erb
<div class="TBK-container">
  <div   iv class="TBK-main-image">
    <%= image_tag "oneclick.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

	<h1>Autorizar transacción</h1>
	<p>
		En este paso autorizaremos una transacción en la tarjeta inscrita.
	<div class="TBK-content-left">
		<div>
			<h3>Petición</h3>
			<p>Una vez que ya tenemos el username y el tbk_user podemos autorizar transacciones en la tarjeta inscrita.</p>
		</div>
		<%= render_markdown_highlighting("oneclick_mall_deferred/partials/authorize-mark1.md") %>
	</div>

	<div class="TBK-content-right">
	  <%= render_markdown_highlighting("shared/resp_to_json.md") %>
		<div class="item-right">
			<h3>Respuesta</h3>
			<p>Una vez autorizada la transacción, estos serán los datos de respuesta</p>
		</div>
	</div>


	<h2>Casi listo !</h2>
		<p class="mb-40">
		Ya puedes mostrar al usuario una página de éxito de la transacción. Debes tener en cuenta que la transacción aun no ha sido capturada solo
		ha sido retenido el saldo en la tarjeta del Tarjetahabiente. Luego de confirmar la transacción podemos:
	</p>
		mark
	<%= render "/deferred/deferred-options" %>

</div>

app/views/oneclick_mall_deferred/delete.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "oneclick.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h2>Eliminar inscripción</h2>
  <p>
    En este paso eliminaremos la inscripción.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>Necesitas el userName (Nombre de Usuario) y el tbkUser y llamar a Oneclick::MallInscription</p>
    </div>
    <%= render_markdown_highlighting("oneclick_mall_deferred/partials/delete-mark1.md") %>
  </div>

  <h2>Respuesta</h2>
  <p>
    En caso de éxito Transbank responderá con un status code 204 (No Content) y el sdk no retornará respuesta. En el caso de no encontrarse el userName o tbkUser Transbank responderá con un status code 404 (Not Found) y el sdk retornara una excepción.
  </p>
  

</div>

app/views/oneclick_mall_deferred/finish.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "oneclick.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h2>Finalizar inscripción</h2>
  <p>
    En este paso terminaremos la inscripción, para luego poder hacer cargos cargos a la tarjeta que el tarjetahabiente inscriba.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Datos recibidos</h3>
      <p>Luego de que se termina el flujo en el formulario de inscripción recibirás un POST con lo siguiente</p>
    </div>
    <%= render_markdown_highlighting("oneclick_mall_deferred/partials/finish-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("oneclick_mall_deferred/partials/finish-mark2.md") %>

    <div class="item-right">
      <h3>Petición</h3>
      <p>Usaras el token recibido para autorizar la transacción usando nuevamente Oneclick</p>
    </div>
  </div>

  <div class="TBK-content-left">
    <div>
      <h3>Respuesta</h3>
      <p>
        Transbank contestará con lo siguiente. Debes guardar esta información. Para poder luego autorizar transacciones vas a necesitar el tbk_user
      </p>
    </div>
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
  </div>

  <h2>La tarjeta ya está inscrita!</h2>
  <h3>Autorizar una transacción</h3>
  <p>Para autorizar una transacción debes guardar datos de la respuesta necesarios</p>

  <div class="TBK-table">
    <div class="TBK-table_cell">
      <p class="text-head">Campo</p>
      <p class="text-head">valor</p>
    </div>
    <div class="TBK-table_cell">
      <p class="main-text"> Nombre de usuario (username)</p>
      <p><%= @user_name %></p>
    </div>
    <div class="TBK-table_cell">
      <p class="main-text">TBK User (tbk_user)</p>
      <p><%= @token %></p>
    </div>
  </div>

  <div class="separed">
    <%= link_to "AUTHORIZAR PAGO", oneclick_mall_deferred_authorize_path(tbk_user: @resp["tbk_user"]), class:"TBK-button j-self-start" %>
    <%= form_with url: '/oneclick_mall_deferred/delete', data: { remote: false }, method: :post do |form| %>
      <%= form.hidden_field  :_method, value: 'delete' %>
      <%= form.hidden_field :user_name, value: @user_name %>
      <%= form.hidden_field :tbk_user, value: @resp["tbk_user"] %>
      <%= form.submit "BORRAR USUARIO", class: "TBK-button" %>
    <% end %>
  </div>


</div>

app/views/oneclick_mall_deferred/show_capture.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "wepayplus.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>
  <h1>Confirmar Transacción diferida</h1>
  <p>
    En este paso debemos capturar la transacción para realmente capturar el dinero que 
    habia sido previamente reservado al hacer la transacción
  </p>

  <div class="TBK-content-left">
		<div>
			<h3>Petición</h3>
			<p>
        Para capturar una transacción necesitaremos el Token, Orden de compra,
        Código de autorización y monto a capturar. Se hace de la siguiente manera.
      </p>
		</div>
		<%= render_markdown_highlighting("oneclick_mall_deferred/partials/capture-mark1.md") %>
	</div>

   <div class="TBK-content-right">
	 	<%= render_markdown_highlighting("shared/resp_to_json.md") %>
		<div class="item-right">
			<h3>Respuesta</h3>
			<p>
        Transbank contestará con lo siguiente. Debes guardar esta información,
        lo único que debes validar es que response_code sea igual a cero.
      </p>
		</div>
	</div>

  <h2>Otras utilidades</h2>
  <p>
    Luego de capturada la transacción puedes Reembolsar (reversar o anular) el pago dependiendo de ciertas condiciones comerciales.
    También puedes consultar el estado de la transacción hasta 7 días después de realizada.
  </p>

  <div class="TBK-content-left">
		<%= link_to "CONSULTAR ESTADO", oneclick_mall_deferred_status_path(buy_order: @buy_order), class:"TBK-button j-self-start" %>

		<%= form_with url: "/oneclick_mall_deferred/refund", data: { remote: false }, method: :post do |form| %>
			<%= form.label :child_buy_order, "buy order" %>
			<%= form.text_field :child_buy_order, value: @child_buy_order, class: "TBK-input" %>
			<%= form.label :commerce_code, "child comerce code" %>
			<%= form.text_field :commerce_code, value:  @child_commerce_code, class: "TBK-input" %>
			<%= form.label :parent_buy_order, "parent buy order" %>
			<%= form.text_field :buy_order, value:  @buy_order, class: "TBK-input" %>
			<%= form.label :amount, "Monto" %>
			<%= form.text_field :amount, value: @amount, class: "TBK-input" %>
			<%= form.submit "REEMBOLSAR", class: "TBK-button" %>
		<% end %>
	</div>
</div>



	
	

app/views/oneclick_mall_deferred/show_refund.html.erb
<div class="TBK-container">
  <div   iv class="TBK-main-image">
    <%= image_tag "oneclick.png" , alt: "oneclick" , class:"adjusted-image" %>
  </div>
  <h1>Reembolso de Transacción</h1>
  <p>
    Podrás pedir el reembolso del dinero al tarjeta habiente,
    dependiendo del monto y el tiempo transacurrido será una Reversa, Anulación o Anulación parcial.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>
        Necesitas la orden de compra de la transacción, el monto que quieres reversar, el código de comercio de la tienda hijo y el orden de compra del detalle de la transacción, si anulas el monto total puede ser una Reversa o Anulación dependiendo de ciertas condiciones o una Anulación parcial si el monto es menor al total.
        No es posible hacer ni Anulaciones ni Anulaciones parciales en tarjetas que no sean de crédito. Tampoco es posible realizar reembolsos de compras en cuotas.
      </p>
    </div>
  	<%= render_markdown_highlighting("oneclick_mall_deferred/partials/refund-mark1.md") %>
  </div>

  <div class="TBK-content-right">
  	<%= render_markdown_highlighting("shared/resp_to_json.md") %>
    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Transbank contestará con el resultado de la reversa o anulación. En el caso de que la transacción corresponda a una Reversa solo se retorna el parámetro type (REVERSED).</p>
    </div>
  </div>
  

</div>

app/views/oneclick_mall_deferred/start.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "oneclick.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h2>Comenzar inscripción</h2>
  <p>
    En este paso comenzaremos la inscripción para poder en el siguiente paso redirigir al Tarjetahabiente hacia el formulario de inscripción de Oneclick
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>Para comenzar debes importar Oneclick y luego comenzar una inscripción</p>
    </div>
    <%= render_markdown_highlighting("oneclick_mall_deferred/partials/start-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>

    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Una vez iniciada la inscripción, estos serán los datos de respuesta</p>
    </div>
  </div>

   <div class="TBK-content-left">
    <div>
      <h3>Por último</h3>
      <p>Debes utilizar estos datos para crear un formulario</p>
    </div>
    <%= render_markdown_highlighting("oneclick_mall_deferred/partials/start-mark2.md") %>
  </div>

  <h2>Ejemplo</h2>

  <div class="TBK-content-left">
    <div>
      <h3>Creamos la transacción</h3>
      <p>Usando los siguientes datos</p>
      <div class="TBK-table">
        <div class="TBK-table_cell">
          <p class="text-head">Campo</p>
          <p class="text-head">valor</p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text"> Nombre de Usuario (userName)</p>
          <p><%= @user_name %></p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text">Email</p>
          <p><%= @email %></p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text"> URL de respuesta (responseUrl)</p>
          <p><%= @response_url %></p>
        </div>
      </div>
    </div>

    <div>
      <h3>Por último</h3>
      <p>Con la respuesta del servicio creamos el formulario, para efectos del ejemplo haremos el campo TBK_TOKEN visible</p>
      <div class="TBK-card">
        <p class="mb-40">Formulario de redirección</p>
        <%= form_with url: @resp["url_webpay"], data: { remote: false }, method: :post do |form| %>
         <%= form.label :TBK_TOKEN, "Token" %>
          <%= form.text_field :TBK_TOKEN, value: @resp["token"], class: "TBK-input" %>
          <%= form.submit "INSCRIBIR", class: "TBK-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/oneclick_mall_deferred/status.html.erb
<div class="TBK-container">
  <div   iv class="TBK-main-image">
    <%= image_tag "oneclick.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h1>Estado de Transacción</h1>
  <p>
    Con esta operación podemos solicitar el estado de una transacción
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>Necesitas el token de la transacción de la cual quieres obtener el estado y con ello llamar nuevamente a WebpayPlus::Transaction.</p>
    </div>
    <%= render_markdown_highlighting("oneclick_mall_deferred/partials/status-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Transbank contestará con lo siguiente. Si no lo hiciste ya, debes guardar esta información, lo único que debes validar es que response_code sea igual a cero.</p>
    </div>
  </div>
</div>