config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'product_index#index'

  get '/webpay_plus/create', to: 'webpay_plus#create'
  get '/webpay_plus/commit', to: 'webpay_plus#commit'
  get '/webpay_plus/status', to: 'webpay_plus#status'
  post '/webpay_plus/refund', to: 'webpay_plus#refund'
  get '/webpay_plus/refund', to: 'webpay_plus#show_refund'

  get '/webpay_plus_deferred/create', to: 'webpay_plus_deferred#create'
  get '/webpay_plus_deferred/commit', to: 'webpay_plus_deferred#commit'
  post '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#capture'
  get '/webpay_plus_deferred/capture', to: 'webpay_plus_deferred#show_capture'
  get '/webpay_plus_deferred/status', to: 'webpay_plus_deferred#status'
  post '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#refund'
  get '/webpay_plus_deferred/refund', to: 'webpay_plus_deferred#show_refund'
  # post '/webpay_plus_deferred/increase_amount', to: 'webpay_plus_deferred#increase_amount'
  # post '/webpay_plus_deferred/reverse', to: 'webpay_plus_deferred#reverse'
  # post '/webpay_plus_deferred/increase_date', to: 'webpay_plus_deferred#increase_date'
  # post '/webpay_plus_deferred/history', to: 'webpay_plus_deferred#history'

  get '/webpay_plus_mall/create', to: 'webpay_plus_mall#create'
  get '/webpay_plus_mall/commit', to: 'webpay_plus_mall#commit'
  get '/webpay_plus_mall/status', to: 'webpay_plus_mall#status'
  post '/webpay_plus_mall/refund', to: 'webpay_plus_mall#refund'
  get '/webpay_plus_mall/refund', to: 'webpay_plus_mall#show_refund'

  get '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#create'
  post '/webpay_plus_mall_deferred/create', to: 'webpay_plus_mall_deferred#send_create'
  get '/webpay_plus_mall_deferred/commit', to: 'webpay_plus_mall_deferred#commit'
  post 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#capture'
  get 'webpay_plus_mall_deferred/capture', to: 'webpay_plus_mall_deferred#show_capture'
  get '/webpay_plus_mall_deferred/status', to: 'webpay_plus_mall_deferred#status'
  post '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#refund'
  get '/webpay_plus_mall_deferred/refund', to: 'webpay_plus_mall_deferred#show_refund'
  # post '/webpay_plus_mall_deferred/increase_amount', to: 'webpay_plus_mall_deferred#increase_amount'
  # post '/webpay_plus_mall_deferred/reverse', to: 'webpay_plus_mall_deferred#reverse'
  # post '/webpay_plus_mall_deferred/increase_date', to: 'webpay_plus_mall_deferred#increase_date'
  # post '/webpay_plus_mall_deferred/history', to: 'webpay_plus_mall_deferred#history'

  get '/oneclick_mall/start', to: 'oneclick_mall#start'
  get '/oneclick_mall/finish', to: 'oneclick_mall#finish'
  delete '/oneclick_mall/delete', to: 'oneclick_mall#delete'
  get '/oneclick_mall/authorize', to: 'oneclick_mall#authorize'
  get '/oneclick_mall/status', to: 'oneclick_mall#status'
  post '/oneclick_mall/refund', to: 'oneclick_mall#refund'
  get '/oneclick_mall/refund', to: 'oneclick_mall#show_refund'

  get '/oneclick_mall_deferred/start', to: 'oneclick_mall_deferred#start'
  get '/oneclick_mall_deferred/finish', to: 'oneclick_mall_deferred#finish'
  delete '/oneclick_mall_deferred/delete', to: 'oneclick_mall_deferred#delete'
  get '/oneclick_mall_deferred/authorize', to: 'oneclick_mall_deferred#authorize'
  get '/oneclick_mall_deferred/status', to: 'oneclick_mall_deferred#status'
  post '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#refund'
  get '/oneclick_mall_deferred/refund', to: 'oneclick_mall_deferred#show_refund'
  post '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#capture'
  get '/oneclick_mall_deferred/capture', to: 'oneclick_mall_deferred#show_capture'
  # post '/oneclick_mall_deferred/increase_amount', to: 'oneclick_mall_deferred#increase_amount'
  # post '/oneclick_mall_deferred/reverse', to: 'oneclick_mall_deferred#reverse'
  # post '/oneclick_mall_deferred/increase_date', to: 'oneclick_mall_deferred#increase_date'
  # post '/oneclick_mall_deferred/history', to: 'oneclick_mall_deferred#history'

  get '/transaccion_completa/form', to: 'transaccion_completa#form'
  post '/transaccion_completa/create', to: 'transaccion_completa#create'
  get '/transaccion_completa/create', to: 'transaccion_completa#show_create'
  post '/transaccion_completa/installments', to: 'transaccion_completa#installments'
  get '/transaccion_completa/installments', to: 'transaccion_completa#show_installments'
  post '/transaccion_completa/commit', to: 'transaccion_completa#commit'
  get '/transaccion_completa/commit', to: 'transaccion_completa#show_commit'
  get  '/transaccion_completa/status', to: 'transaccion_completa#status'
  post '/transaccion_completa/refund', to: 'transaccion_completa#refund'
  get '/transaccion_completa/refund', to: 'transaccion_completa#show_refund'

  get '/transaccion_completa_deferred/form', to: 'transaccion_completa_deferred#form'
  post '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#create'
  get '/transaccion_completa_deferred/create', to: 'transaccion_completa_deferred#show_create'
  post '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#installments'
  get '/transaccion_completa_deferred/installments', to: 'transaccion_completa_deferred#show_installments'
  post '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#commit'
  get '/transaccion_completa_deferred/commit', to: 'transaccion_completa_deferred#show_commit'
  post '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#capture'
  get '/transaccion_completa_deferred/capture', to: 'transaccion_completa_deferred#show_capture'
  get  '/transaccion_completa_deferred/status', to: 'transaccion_completa_deferred#status'
  post '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#refund'
  get '/transaccion_completa_deferred/refund', to: 'transaccion_completa_deferred#show_refund'
  # post '/transaccion_completa_deferred/increase_amount', to: 'transaccion_completa_deferred#increase_amount'
  # post '/transaccion_completa_deferred/reverse', to: 'transaccion_completa_deferred#reverse'
  # post '/transaccion_completa_deferred/increase_date', to: 'transaccion_completa_deferred#increase_date'
  # post '/transaccion_completa_deferred/history', to: 'transaccion_completa_deferred#history'

  get '/transaccion_completa_mall/form', to: 'transaccion_completa_mall#form'
  post '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#create'
  get '/transaccion_completa_mall/create', to: 'transaccion_completa_mall#show_create'
  post '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#installments'
  get '/transaccion_completa_mall/installments', to: 'transaccion_completa_mall#show_installments'
  post '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#commit'
  get '/transaccion_completa_mall/commit', to: 'transaccion_completa_mall#show_commit'
  get  '/transaccion_completa_mall/status', to: 'transaccion_completa_mall#status'
  post '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#refund'
  get '/transaccion_completa_mall/refund', to: 'transaccion_completa_mall#show_refund'

  get '/transaccion_completa_mall_deferred/form', to: 'transaccion_completa_mall_deferred#form'
  post '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#create'
  get '/transaccion_completa_mall_deferred/create', to: 'transaccion_completa_mall_deferred#show_create'
  post '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#installments'
  get '/transaccion_completa_mall_deferred/installments', to: 'transaccion_completa_mall_deferred#show_installments'
  post '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#commit'
  get '/transaccion_completa_mall_deferred/commit', to: 'transaccion_completa_mall_deferred#show_commit'
  post '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#capture'
  get '/transaccion_completa_mall_deferred/capture', to: 'transaccion_completa_mall_deferred#show_capture'
  get  '/transaccion_completa_mall_deferred/status', to: 'transaccion_completa_mall_deferred#status'
  post '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#refund'
  get '/transaccion_completa_mall_deferred/refund', to: 'transaccion_completa_mall_deferred#show_refund'
  # post '/transaccion_completa_mall_deferred/increase_amount', to: 'transaccion_completa_mall_deferred#increase_amount'
  # post '/transaccion_completa_mall_deferred/reverse', to: 'transaccion_completa_mall_deferred#reverse'
  # post '/transaccion_completa_mall_deferred/increase_date', to: 'transaccion_completa_mall_deferred#increase_date'
  # post '/transaccion_completa_mall_deferred/history', to: 'transaccion_completa_mall_deferred#history'

  get '/patpass_comercio/start', to: 'patpass_comercio#start'
  post '/patpass_comercio/commit', to: 'patpass_comercio#commit'
  post '/patpass_comercio/commit', to: 'patpass_comercio#show_commit'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#voucher_return'
  post '/patpass_comercio/voucher_return', to: 'patpass_comercio#show_voucher_return'

end

app/controllers/webpay_plus_deferred_controller.rb
class WebpayPlusDeferredController < ApplicationController
  skip_before_action :verify_authenticity_token

  def initialize
    super 
    @tx = Transbank::Webpay::WebpayPlus::Transaction.new(::Transbank::Common::IntegrationCommerceCodes::WEBPAY_PLUS_DEFERRED, ::Transbank::Common::IntegrationApiKeys::WEBPAY, :integration)
    @ctrl = "webpay_plus_deferred"
  end

  def create
    @req = params.as_json
    @buy_order = "buyOrder_#{rand(1000)}"
    @session_id = "sessionId_#{rand(1000)}"
    @amount = 1000
    @return_url = "#{root_url}#{@ctrl}/commit"
    @resp = @tx.create(@buy_order, @session_id, @amount, @return_url)
  end

  def commit
    @req = params.as_json
    @token = params[:token_ws]
    @resp = @tx.commit(@token)
    

    @amount = @resp['amount']
    @buy_order = @resp['buy_order']
    @authorization_code = @resp['authorization_code']
  end

  def refund
    @req = params.as_json
    @token = params[:token]
    @amount = params[:amount]
    @resp = @tx.refund(@token, @amount)
     

    redirect_to webpay_plus_deferred_refund_path(token: @token, amount: @amount, resp: @resp)
  end

  def show_refund
    @token = params[:token]
    @amount = params[:amount]
    @resp = params[:resp]
  end

  def status
    @req = params.as_json
    @token = params[:token]
    @resp = @tx.status(@token)
    
  end

  def capture
    @req = params.as_json
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = @tx.capture(@token, @buy_order, @authorization_code, @amount)  
    
    redirect_to webpay_plus_deferred_capture_path(token: @token, buy_order: @buy_order, authorization_code: @authorization_code, amount: @amount, resp: @resp)
  end

  def show_capture
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = params[:resp]
  end

  def increase_amount
    @req = params.as_json
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = @tx.increase_amount(@token, @buy_order, @authorization_code, @amount)
    
    @amount = @resp['total_amount']
  end

  def increase_date
    @req = params.as_json
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = @tx.increase_authorization_date(@token, @buy_order, @authorization_code)
    
    @amount = @resp['total_amount']
  end

  def reverse
    @req = params.as_json
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = @tx.reverse_pre_authorized_amount(@token, @buy_order, @authorization_code, @amount) 
    
    @amount = @resp['total_amount']
  end

  def history
    @req = params.as_json
    @token = params[:token]
    @buy_order = params[:buy_order]
    @authorization_code = params[:authorization_code]
    @amount = params[:amount]
    @resp = @tx.deferred_capture_history(@token)
  end


end

app/views/webpay_plus_deferred/commit.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "wepayplus.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h1>Confirmar Transacción diferida</h1>
	<p>
		En este paso tenemos que confirmar la transacción con el objetivo de avisar a Transbank que
    hemos recibido la transacción ha sido recibida exitosamente. En caso de que no se confirme la transacción, ésta será reversada.
	</p>

  <div class="TBK-content-left">
		<div>
			<h3>Datos recibidos</h3>
			<p>Luego de que se termina el flujo en el formulario de pago recibiras un POST con lo siguiente</p>
		</div>
		<%= render_markdown_highlighting("webpay_plus_deferred/partials/commit-mark1.md") %>
	</div>

  <div class="TBK-content-right">
	  <%= render_markdown_highlighting("webpay_plus_deferred/partials/commit-mark2.md") %>
		<div class="item-right">
			<h3>Petición</h3>
			<p>Usaras el token recibido para confirmar la transacción usando nuevamente WebpayPlus</p>
		</div>
	</div>

  <div class="TBK-content-left">
		<div>
			<h3>Respuesta</h3>
			<p>Transbank contestará con lo siguiente. Debes guardar esta información, lo único que debes validar es que response_code sea igual a cero.</p>
		</div>
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
	</div>

  <h2>Casi listo !</h2>
	<p class="mb-40">
    Ya puedes mostrar al usuario una página de éxito de la transacción. Debes tener en cuenta que la transacción aun no ha sido capturada solo
    ha sido retenido el saldo en la tarjeta del Tarjetahabiente. Luego de confirmar la transacción podemos:
  </p>
markdown
  <%= render "/deferred/deferred-options" %>



</div>

app/views/webpay_plus_deferred/create.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "wepayplus.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h2>Crear Transacción diferida</h2>
  <p>
    En este paso crearemos la transacción con el objetivo de obtener un identificador unico y
    poder en el siguiente paso redirigir al Tarjetahabiente hacia el formulario de pago.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>Para comenzar debes importar WebpayPlus y luego crear una transacción</p>
    </div>
    <%= render_markdown_highlighting("webpay_plus_deferred/partials/create-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>

    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Una vez creada la transacción, estos serán los datos de respuesta</p>
    </div>
  </div>

  <div class="TBK-content-left">
  <div>
    <h3>Por último</h3>
    <p>Debes utilizar estos datos para crear un formulario</p>
  </div>
  <%= render_markdown_highlighting("webpay_plus_deferred/partials/create-mark2.md") %>
  </div>

  <h2>Ejemplo</h2>

  <div class="TBK-content-left">
    <div>
      <h3>Creamos la transacción</h3>
      <p>Usando los siguientes datos</p>
      <div class="TBK-table">
        <div class="TBK-table_cell">
          <p class="text-head">Campo</p>
          <p class="text-head">valor</p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text"> Orden de compra(buyOrder)</p>
          <p><%= @buy_order%></p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text">ID de sesión (sessionid)</p>
          <p><%= @session_id%></p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text"> Monto (amount)</p>
          <p><%= @amount%></p>
        </div>
        <div class="TBK-table_cell">
          <p class="main-text"> URL de retorno (returnUrl)</p>
          <p class="break-word" title="dw"><%= @return_url%></p>
        </div>
      </div>
    </div>

    <div>
      <h3>Por último</h3>
      <p>Con la respuesta del servicio creamos el formulario, para efectos del ejemplo haremos el campo token_ws visible</p>
      <div class="TBK-card">
        <p class="mb-40">Formulario de redirección</p>
        <%= form_with url: @resp["url"], data: { remote: false }, method: :post do |form| %>
          <%= form.label :token_ws, "Token" %>
          <%= form.text_field :token_ws, value: @resp["token"], class: "TBK-input" %>
          <%= form.submit "PAGAR", class: "TBK-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/webpay_plus_deferred/show_capture.html.erb
<div class="TBK-container">
  <div class="TBK-main-image">
    <%= image_tag "wepayplus.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>
  <h1>Confirmar Transacción diferida</h1>
  <p>
    En este paso debemos capturar la transacción para realmente capturar el dinero que 
    habia sido previamente reservado al hacer la transacción
  </p>

  <div class="TBK-content-left">
		<div>
			<h3>Petición</h3>
			<p>
        Para capturar una transacción necesitaremos el Token, Orden de compra,
        Código de autorización y monto a capturar. Se hace de la siguiente manera.
      </p>
		</div>
    <%= render_markdown_highlighting("webpay_plus_deferred/partials/create-mark1.md") %>
	</div>

   <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
		<div class="item-right">
			<h3>Respuesta</h3>
			<p>
        Transbank contestará con lo siguiente. Debes guardar esta información,
        lo único que debes validar es que response_code sea igual a cero.
      </p>
		</div>
	</div>

  <h2>Otras utilidades</h2>
  <p>
    Luego de capturada la transacción puedes Reembolsar (reversar o anular) el pago dependiendo de ciertas condiciones comerciales.
    También puedes consultar el estado de la transacción hasta 7 días después de realizada.
  </p>

  <div class="TBK-content-left">
		<%= link_to "CONSULTAR ESTADO", webpay_plus_deferred_status_path(token: @token), class:"TBK-button j-self-start" %>
		<%= form_with url: "/webpay_plus_deferred/refund", data: { remote: false }, method: :post do |form| %>
			<%= form.hidden_field  :token, value: @token, class: "TBK-input" %>
			<%= form.label :amount, "Monto" %>
			<%= form.text_field    :amount, value:  @amount, class: "TBK-input" %>
			<%= form.submit "REEMBOLSAR", class: "TBK-button" %>
		<% end %>
	</div>
</div>

app/views/webpay_plus_deferred/show_refund.html.erb
<div class="TBK-container">
  <div   iv class="TBK-main-image">
    <%= image_tag "wepayplus.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>
  <h1>Reembolso de Transacción diferida</h1>
  <p>
    Podrás pedir el reembolso del dinero al tarjeta habiente,
    dependiendo del monto y el tiempo transacurrido será una Reversa, Anulación o Anulación parcial.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>
        Necesitas el token de la transacción y el monto que quieres reversar,
        si anulas el monto total puede ser una Reversa o Anulación dependiendo de ciertas condiciones
        o una Anulación parcial si el monto es menor al total.
        No es posible hacer ni Anulaciones ni Anulaciones parciales en tarjetas que no sean de crédito.
        Tampoco es posible realizar reembolsos de compras en cuotas.
      </p>
    </div>
    <%= render_markdown_highlighting("webpay_plus_deferred/partials/refund-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Transbank contestará con el resultado de la reversa o anulación.</p>
    </div>
  </div>
  

</div>

app/views/webpay_plus_deferred/status.html.erb
<div class="TBK-container">
  <div   iv class="TBK-main-image">
    <%= image_tag "wepayplus.png" , alt: "webpayplus" , class:"adjusted-image" %>
  </div>

  <h1>Estado de Transacción diferida</h1>
  <p>
    Puedes solicitar el estado de una transacción hasta 7 días despues de que haya sido realizada.
    No hay limite de solicitudes de este tipo, sin embargo, una vez pasados los 7 días ya no podrás revisar su estado.
  </p>

  <div class="TBK-content-left">
    <div>
      <h3>Petición</h3>
      <p>Necesitas el token de la transacción de la cual quieres obtener el estado y con ello llamar nuevamente a WebpayPlus::Transaction.</p>
    </div>
    <%= render_markdown_highlighting("webpay_plus_deferred/partials/status-mark1.md") %>
  </div>

  <div class="TBK-content-right">
    <%= render_markdown_highlighting("shared/resp_to_json.md") %>
    <div class="item-right">
      <h3>Respuesta</h3>
      <p>Transbank contestará con lo siguiente. Si no lo hiciste ya, 
      debes guardar esta información, lo único que debes validar es que response_code sea igual a cero.</p>
    </div>
  </div>

</div>